### ISSUE TITLE
Missing symbols

### ISSUE THREAD

**Issue by luk-f-a** [IntelPython/sdc#952]
hello!

I tried running the latest version of sdc and got this problem when importing:

```python
/home/.../anaconda3/envs/sdc-env/bin/python /home/.../mypyprojects/test_intel_sdc/test.py
Traceback (most recent call last):
  File "/home/.../mypyprojects/test_intel_sdc/test.py", line 1, in <module>
    import sdc
  File "/home//anaconda3/envs/sdc-env/lib/python3.7/site-packages/sdc/__init__.py", line 38, in <module>
    import sdc.hiframes.boxing
  File "/home//anaconda3/envs/sdc-env/lib/python3.7/site-packages/sdc/hiframes/boxing.py", line 58, in <module>
    from sdc.extensions.indexes.range_index_ext import box_range_index, unbox_range_index
  File "/home//anaconda3/envs/sdc-env/lib/python3.7/site-packages/sdc/extensions/indexes/range_index_ext.py", line 41, in <module>
    from sdc.datatypes.common_functions import SDCLimitation, _sdc_take
  File "/home//anaconda3/envs/sdc-env/lib/python3.7/site-packages/sdc/datatypes/common_functions.py", line 48, in <module>
    from sdc.functions import numpy_like
  File "/home//anaconda3/envs/sdc-env/lib/python3.7/site-packages/sdc/functions/numpy_like.py", line 59, in <module>
    from sdc.functions.sort import parallel_sort, parallel_stable_sort, parallel_argsort, parallel_stable_argsort
  File "/home//anaconda3/envs/sdc-env/lib/python3.7/site-packages/sdc/functions/sort.py", line 36, in <module>
    from sdc import concurrent_sort
ImportError: //.../anaconda3/envs/sdc-env/lib/python3.7/site-packages/sdc/concurrent_sort.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN3tbb6detail2r114notify_waitersERNS0_2d112wait_contextE
```

This is linux mint 19.1 64bit, python 3.7.

This is the full environment, which was created fresh following the instructions in the readme:

<details>
  <summary> Package list - Click to expand!</summary>
  
```
# Name                    Version                   Build  Channel
abseil-cpp                20200225.2           he1b5a44_2    conda-forge
arrow-cpp                 0.17.0           py37hc11a6a2_0    conda-forge
aws-sdk-cpp               1.7.164              hba45d7a_2    conda-forge
blas                      1.0                         mkl    anaconda
boost-cpp                 1.72.0               h9d3c048_4    conda-forge
brotli                    1.0.9                he6710b0_2    anaconda
bzip2                     1.0.8                h7b6447c_0    anaconda
c-ares                    1.16.1               h7b6447c_0    anaconda
ca-certificates           2020.10.14                    0    anaconda
certifi                   2020.6.20        py37hefe589e_1    intel
curl                      7.71.1               hbc83047_1    anaconda
gflags                    2.2.2                he6710b0_0    anaconda
glog                      0.4.0                he6710b0_0    anaconda
grpc-cpp                  1.28.1               h8e748ff_2    conda-forge
icc_rt                    2020.3                intel_304    intel
icu                       68.1                 h58526e2_0    conda-forge
intel-openmp              2020.2                      254    anaconda
intelpython               2021.1.1                      1    intel
krb5                      1.18.2               h173b8e3_0    anaconda
ld_impl_linux-64          2.33.1               h53a641e_7    anaconda
libcurl                   7.71.1               h20c2e04_1    anaconda
libedit                   3.1.20191231         h14c3975_1    anaconda
libevent                  2.1.10               hcdb4288_3    conda-forge
libffi                    3.3                  he6710b0_2    anaconda
libgcc-ng                 9.1.0                hdf63c60_0    anaconda
libllvm10                 10.0.1               hbcb73fb_5  
libprotobuf               3.11.4               hd408876_0    anaconda
libssh2                   1.9.0                h1ba5d50_1    anaconda
libstdcxx-ng              9.1.0                hdf63c60_0    anaconda
libthrift                 0.13.0               hbe8ec66_6    conda-forge
llvmlite                  0.34.0           py37h269e1b5_4  
lz4-c                     1.9.2                heb0550a_3    anaconda
mkl                       2019.4                      243    anaconda
mkl-service               2.3.0            py37he904b0f_0    anaconda
mkl_fft                   1.2.0            py37h23d657b_0    anaconda
mkl_random                1.1.0            py37hd6b4f25_0    anaconda
ncurses                   6.2                  he6710b0_1    anaconda
numba                     0.51.2           py37h35a63e4_0    intel
numpy                     1.19.1           py37hbc911f0_0    anaconda
numpy-base                1.19.1           py37hfa32c7d_0    anaconda
openssl                   1.1.1h               h14c3975_0    intel
pandas                    1.0.5            py37h0573a6f_0    anaconda
parquet-cpp               1.5.1                         2    conda-forge
pip                       20.2.4                   py37_0    anaconda
pyarrow                   0.17.0           py37h110162e_0    conda-forge
python                    3.7.9                h7579374_0    anaconda
python-dateutil           2.8.1                      py_0    anaconda
python_abi                3.7                     1_cp37m    conda-forge
pytz                      2020.1                     py_0    anaconda
re2                       2019.08.01           he6710b0_0    anaconda
readline                  8.0                  h7b6447c_0    anaconda
sdc                       0.36.0           py37he107479_0    intel/label/beta
setuptools                50.3.0           py37hb0f4dca_1    anaconda
six                       1.15.0                     py_0    anaconda
snappy                    1.1.8                he6710b0_0    anaconda
sqlite                    3.33.0               h62c20be_0    anaconda
tbb                       2021.1.1              intel_119    intel
tbb4py                    2021.1.1         py37_intel_119    intel
thrift-compiler           0.13.0               hbe8ec66_6    conda-forge
thrift-cpp                0.13.0                        6    conda-forge
tk                        8.6.10               hbc83047_0    anaconda
wheel                     0.35.1                     py_0    anaconda
xz                        5.2.5                h7b6447c_0    anaconda
zlib                      1.2.11               h7b6447c_3    anaconda
zstd                      1.4.5                h9ceee32_0    anaconda
```

</details>

Is this a problem with the TBB version? https://github.com/intel/llvm/issues/2774

**Comment by AlexanderKalistratov** [comment]
@luk-f-a thanks for reporting. It seems there was wrong label on conda channel, resulting older version of sdc (0.36) is downloading. At the moment labels are fixed and correct version (0.37) should be download.

Please check if it fixes your issue.

**Comment by luk-f-a** [comment]
hi @AlexanderKalistratov , thanks, problem solved!
